In [1]:
import numpy as np
import pandas as pd

import sklearn
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv('https://www.dropbox.com/s/9t04t1haanbdvvt/bank-data-for-pca.csv?dl=1')
df

,Возраст,Работа,Семейный статус,Образование,Кредитный дефолт,Ипотека,Займ,Контакт,Месяц,День недели,Длительность,Кампания,Предыдущий контакт,Доходность,Колебание уровня безработицы,Индекс потребительских цен,Индекс потребительской уверенности,Европейская межбанковская ставка,Количество сотрудников в компании,y
0,27.0,Самозанятый,Не женат / не замужем,Университетская степень,Нет,Нет,Нет,Городской телефон,Октябрь,5,24.0,1.0,0.0,Отсутствует,-0.1,93.798,-40.4,5.045,5195.0,Нет
1,30.0,Преддприниматель,Женат / замужем,Университетская степень,Нет,Нет,Нет,Городской телефон,Октябрь,5,223.0,1.0,0.0,Отсутствует,-0.1,93.798,-40.4,5.045,5195.0,Да
2,39.0,Голубой воротничок,Женат / замужем,Базовое (9 классов),Нет,Нет,Нет,Городской телефон,Октябрь,5,270.0,1.0,0.0,Отсутствует,-0.1,93.798,-40.4,5.045,5195.0,Да
3,42.0,Менеджер,Женат / замужем,Высшая школа,Нет,Да,Да,Городской телефон,Октябрь,5,103.0,1.0,0.0,Отсутствует,-0.1,93.798,-40.4,5.045,5195.0,Да
4,42.0,Самозанятый,Женат / замужем,Базовое (4 класса),Нет,Нет,Нет,Городской телефон,Октябрь,5,478.0,1.0,0.0,Отсутствует,-0.1,93.798,-40.4,5.045,5195.0,Да
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41171,68.0,Пенсионер,Разведен(-а),Высшая школа,Нет,Да,Нет,Сотовый телефон,Октябрь,1,222.0,1.0,0.0,Отсутствует,-1.1,94.601,-49.5,1.000,4963.0,Да
41172,68.0,Пенсионер,Разведен(-а),Высшая школа,Нет,Да,Да,Сотовый телефон,Октябрь,1,567.0,1.0,1.0,Присутствует,-1.1,94.601,-49.5,1.000,4963.0,Да
41173,74.0,Пенсионер,Разведен(-а),Базовое (4 класса),Нет,Да,Нет,Сотовый телефон,Октябрь,1,102.0,3.0,2.0,Присутствует,-1.1,94.601,-49.5,1.000,4963.0,Нет
41174,74.0,Пенсионер,Разведен(-а),Базовое (4 класса),Нет,Да,Нет,Сотовый телефон,Октябрь,1,180.0,2.0,0.0,Отсутствует,-1.1,94.601,-49.5,1.000,4963.0,Нет
41175,84.0,Пенсионер,Разведен(-а),Базовое (4 класса),Неизвестно,Да,Да,Сотовый телефон,Октябрь,1,138.0,4.0,1.0,Присутствует,-1.1,94.601,-49.5,1.000,4963.0,Нет

In [3]:
X = df[['Возраст', 'Длительность', 'Кампания', 'День недели', 'Предыдущий контакт', 'Индекс потребительских цен', 'Европейская межбанковская ставка', 'Количество сотрудников в компании']]
y = df.iloc[:, -1]

In [7]:
x = StandardScaler().fit_transform(X)
pd.DataFrame(x).head()

,0,1,2,3,4,5,6,7
0,-1.249818,-0.903640,-0.565963,1.431363,-0.349551,0.384015,0.820856,0.389225
1,-0.961926,-0.136196,-0.565963,1.431363,-0.349551,0.384015,0.820856,0.389225
2,-0.098248,0.045060,-0.565963,1.431363,-0.349551,0.384015,0.820856,0.389225
3,0.189644,-0.598976,-0.565963,1.431363,-0.349551,0.384015,0.820856,0.389225
4,0.189644,0.847213,-0.565963,1.431363,-0.349551,0.384015,0.820856,0.389225

In [8]:
pca = PCA(n_components = 1)

principalComponents = pca.fit_transform(x)
principalDf = pd.DataFrame(data = principalComponents, columns = ['principal component 1'])

principalDf.head()

   principal component 1
0              -0.946370
1              -0.918696
2              -0.907002
3              -0.926795
4              -0.878160